<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>

<script src="resources/js/jquery/jQuery.js"></script>
<script src="resources/js/jquery/jQuery-UI.js"></script>
<script src="resources/js/jquery/jQuery_Mobile.js"></script>

<!--<script src="resources/js/bootstrap/bootstrap.min.js"></script>-->
<script src="resources/js/Angular/angularJs.js"></script>

<script src="resources/js/custom/functions.js"></script>
<script src="resources/js/custom/angularApp.js"></script>
<script src="resources/js/custom/ajax.js"></script>

<!--<link rel="stylesheet" href="resources/css/bootstrap/bootstrap.min.css">-->
<link rel="stylesheet" href="resources/css/jquery/jQuery_Mobile.css">

<link rel='stylesheet' media='screen and (min-width: 1020px)' href='resources/css/custom/pc.css' />
<link rel='stylesheet' media='screen and (min-width: 530px) and (max-width: 1020px)' href='resources/css/custom/tablet.css' />
<link rel="stylesheet" media="screen and (min-width : 296px) and (max-width : 530px)" href="resources/css/custom/mobile.css" />

<link rel="stylesheet" media="screen and (min-width : 296px) and (max-width : 530px)" href="resources/css/custom/myOverrideCss.css" />

